### ISSUE TITLE
HRP4.3.6使用新版本的funpluginn初始化报错

### ISSUE THREAD

**Issue by paololu** [httprunner/funplugin#8]
hrp4.3.6 版本在windows环境初始化时判断funppy 版本执行命令报错了
[INFO]  fungo: ensure python3 venv: python3=C:\Users\Paolo\.hrp\venv\Scripts\python.exe packages=["funppy"]
[INFO]  fungo: exec command: cmd=C:\WINDOWS\system32\cmd.exe
[INFO]  fungo: installing python package: pkgName=funppy pkgVersion=""
[INFO]  fungo: exec command: cmd=C:\WINDOWS\system32\cmd.exe
2023-09-27T10:50:41.81+08:00 ERR python3 venv is not ready error="pip install funppy failed: python package funppy not found" packages=["funppy"]
2023-09-27T10:50:41.811+08:00 ERR [Run] init case runner failed error="init plugin failed: pip install funppy failed: python package funppy not found: prepare python3 venv failed"
Error: init plugin failed: pip install funppy failed: python package funppy not found: prepare python3 venv failed
hrp exit 9

本地调试的时候发现是下面的命令执行报错了：
C:\Users\Paolo>cmd.exe "/c C:\\Users\\Paolo\\.hrp\\venv\\Scripts\\python.exe -c import funppy; print(funppy.__version__)"
  File "<string>", line 1
    import
         ^
SyntaxError: invalid syntax

C:\Users\Paolo>

cmd.go 文件加上\" 可以解决该问题：

```
func AssertPythonPackage(python3 string, pkgName, pkgVersion string) error {
	out, err := Command(
		**python3, "-c", fmt.Sprintf("\"import %s; print(%s.__version__)\"", pkgName, pkgName),**
	).Output()
	if err != nil {
		return fmt.Errorf("python package %s not found", pkgName)
	}

	// do not check version if pkgVersion is empty
	if pkgVersion == "" {
		logger.Info("python package is ready", "name", pkgName)
		return nil
	}

	// check package version equality
	version := strings.TrimSpace(string(out))
	if strings.TrimLeft(version, "v") != strings.TrimLeft(pkgVersion, "v") {
		return fmt.Errorf("python package %s version %s not matched, please upgrade to %s",
			pkgName, version, pkgVersion)
	}

	logger.Info("python package is ready", "name", pkgName, "version", pkgVersion)
	return nil
}
```

**Comment by debugtalk** [comment]
fixed

**Comment by huangxh5** [comment]
如果是Python语言运行的应该修改哪个文件呀，我是hrp4.3.5版本的

**Comment by huangxh5** [comment]
修改 "C:\Users\Xpeng\.hrp\venv\Lib\site-packages\funppy\_init_.py"的__version__字段值为0.5.0可解决，以下为我的样例：
__version__ = 'v0.5.0'

from funppy.plugin import register, serve

__all__ = ["register", "serve"]
